spring:
  application:
    name: catalog
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: admin
    password: secretpassword123
    driver-class-name: org.postgresql.Driver
server:
  port: 8081